inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/OptionalBooleanParameter:
  Enabled: false

Style/Semicolon:
  Exclude:
    - 'spec/**/*.rb'
